### ISSUE TITLE
Doesn't handle "Your" prefix on clippings

### ISSUE THREAD

**Issue by amoe** [gwolf/kindleclip#2]
For some reason my Kindle Paperwhite creates clippings headers that looks like this:

    - Your Bookmark at location 151 | Added on Saturday, 9 May 2015 04:58:57

This causes the program to exit with a parsing error in `read_kind_place_tstamp`.

**Comment by gwolf** [comment]
I have never seen this kind of clipping prefix, if possible please send me a sample "My Clippings.txt" file to check this on.
I have added a patch that will kill any "Your" prefixes and integrate into "Bookmark" handling; please check my commit 879f117 to confirm if it did the trick.
Thanks!

**Comment by amoe** [comment]
[clippings.txt](https://github.com/gwolf/kindleclip/files/58696/clippings.txt)

Hi, I uploaded a sample above, although it's cut down it should still demonstrate the issue.  It now seems to crash with `Unknown item type: ""`.

**Comment by gwolf** [comment]
Sorry for such a long delay! I have had very little free time to play with.

I think I finally nailed it down, and called it a release. It does correctly open your test case now! Please do check if it fixed the problem for you on your "real" data.

I am closing both this and the other pending issue you opened. Of course, feel free to reopen if needed!

**Comment by amoe** [comment]
Yep, this fixed the problem for me.  kindleclip now loads my giant clippings file without any issue at all.  Thanks so much for this.  :)
