### ISSUE TITLE
Doesn't handle "Clip This Article" kind of clipping

### ISSUE THREAD

**Issue by amoe** [gwolf/kindleclip#3]
There is another kind of clipping that you can use in newspaper articles, it copies the entire text of the article and creates a heading that looks like this:

    - Clip This Article at Location 4460 | Added on Thursday, 1 October 2015 09:37:21

This causes an error when parsing the header, much like #2.

**Comment by gwolf** [comment]
Hi,
I only have an older Kindle (3rd generation) and have never seen this clipping type. Could you possibly send me an example "My Clippings" file showing what does it entail, besides this header? I'd not expect it to copy the full newspaper article to the Clippings file...
Anyway, please check with my latest pushed commit (4266957), that will at least allow it to properly parse the file; if it works, I'll add it to the UI (it will for now basically just be ignored).
Thanks!

**Comment by amoe** [comment]
It actually does copy the entire text of the newspaper into the clippings file, removing any whitespace and formatting.

**Comment by gwolf** [comment]
Closing this issue, as it is fixed together with #2 .
